site_name: LaravelPackage.com
repo_url: https://github.com/PackagePages/LaravelPackage.com
repo_name: LaravelPackage.com
edit_uri: edit/master/docs/
theme:
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
  favicon: assets/favicon.ico
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
